print("LIST OF FRIEND LIST")
print("stephen")
print("selvam")
print("raja")
print("alex")
print("joseph")
print("vinoth")
print("abi")
print("shyam")
print("allen")
print("manoj")
print("anand")
print("albert")
